version: '3.8'

services:
  dev:
    build:
      context: .
      dockerfile: Dockerfile
    tty: true
    volumes:
      - ../:/app

  chrome:
    image: selenium/standalone-chrome-debug
    ports:
      - 4444:4444
      - 5900:5900
    volumes:
      - /dev/shm:/dev/shm
